'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomPage
    Public Property ID As Integer
    Public Property Name As String
    Public Property DateCreated As Date
    Public Property CreatedBy As Long
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Long)
    Public Property Status As Byte
    Public Property PageType As Nullable(Of Byte)
    Public Property Sitemap As Boolean

    Public Overridable Property Member As Member
    Public Overridable Property Member1 As Member

End Class
