'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Link
    Public Property ID As Integer
    Public Property LinkGroup As String
    Public Property URL As String
    Public Property Title As String
    Public Property Text As String
    Public Property Target As String
    Public Property ParentID As Nullable(Of Integer)
    Public Property Sequence As Integer

    Public Overridable Property Link1 As ICollection(Of Link) = New HashSet(Of Link)
    Public Overridable Property Link2 As Link

End Class
