'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderItem
    Public Property ID As Integer
    Public Property OrderID As Integer
    Public Property ProductImg As String
    Public Property ProductName As String
    Public Property ProductCode As String
    Public Property Quantity As Integer
    Public Property Price As Decimal
    Public Property Amount As Decimal

    Public Overridable Property Order As Order

End Class
