'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property ID As Integer
    Public Property DateCreated As Date
    Public Property Name As String
    Public Property Email As String
    Public Property MemberID As Nullable(Of Long)
    Public Property Phone As String
    Public Property BillingAddress As String
    Public Property BillingCity As String
    Public Property BillingState As String
    Public Property BillingCountry As String
    Public Property BillingZip As String
    Public Property ShippingAddress As String
    Public Property ShippingCity As String
    Public Property ShippingState As String
    Public Property ShippingCountry As String
    Public Property ShippingZip As String
    Public Property Coupon As String
    Public Property Status As Byte
    Public Property ShippingTrackCode As String
    Public Property ShippingNotes As String
    Public Property DateModified As Date
    Public Property Amount As Decimal
    Public Property Tax As Decimal
    Public Property TaxPercentage As Decimal
    Public Property Discount As Decimal
    Public Property Total As Decimal
    Public Property TransactionCode As String
    Public Property TransactionDate As Nullable(Of Date)
    Public Property TransactionDetail As String
    Public Property ShippingPrice As Decimal
    Public Property COD As Decimal
    Public Property PaymentMode As String
    Public Property ShippingService As String
    Public Property ShippingFirstName As String
    Public Property ShippingLastName As String
    Public Property ShippingPhone As String

    Public Overridable Property Member As Member
    Public Overridable Property OrderItems As ICollection(Of OrderItem) = New HashSet(Of OrderItem)

End Class
