'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PageComment
    Public Property ID As Long
    Public Property MemberID As Nullable(Of Long)
    Public Property Name As String
    Public Property Email As String
    Public Property Website As String
    Public Property MessageText As String
    Public Property CreateDate As Date
    Public Property Status As Byte
    Public Property ModifiedBy As Nullable(Of Long)
    Public Property ModifyDate As Nullable(Of Date)
    Public Property Note As String
    Public Property ParentId As Nullable(Of Long)
    Public Property URL As String
    Public Property CommentType As Byte
    Public Property IPAddress As String

    Public Overridable Property Member As Member
    Public Overridable Property Member1 As Member
    Public Overridable Property PageComment1 As ICollection(Of PageComment) = New HashSet(Of PageComment)
    Public Overridable Property PageComment2 As PageComment

End Class
