'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Post
    Public Property ID As Long
    Public Property Title As String
    Public Property DateCreated As Date
    Public Property DateModified As Nullable(Of Date)
    Public Property CreatedBy As Long
    Public Property ModifiedBy As Nullable(Of Long)
    Public Property Category As Integer
    Public Property Tag As String
    Public Property Status As Byte
    Public Property Description As String
    Public Property Article As String
    Public Property WriterName As String
    Public Property WriterEmail As String
    Public Property OGImage As String
    Public Property OGDescription As String
    Public Property Viewed As Integer
    Public Property URL As String
    Public Property Sitemap As Boolean
    Public Property MetaTitle As String

    Public Overridable Property Category1 As Category
    Public Overridable Property Member As Member
    Public Overridable Property Member1 As Member
    Public Overridable Property TopStories As ICollection(Of TopStory) = New HashSet(Of TopStory)

End Class
