'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductTag
    Public Property ID As Integer
    Public Property ProductID As Integer
    Public Property TagID As Integer

    Public Overridable Property CategoryTag As CategoryTag
    Public Overridable Property Product As Product

End Class
