'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TopStory
    Public Property id As Integer
    Public Property PostId As Long
    Public Property CreatedBy As Long
    Public Property DateCreated As Date

    Public Overridable Property Member As Member
    Public Overridable Property Post As Post

End Class
