'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Communicate

    '''<summary>
    '''EmailGroupTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailGroupTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EmailGroupReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailGroupReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SubjectTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubjectTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubjectReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubjectReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EmailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EmailReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PreviewLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviewLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''OrderEmailsChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderEmailsChk As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''RegisterMemberChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegisterMemberChk As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
End Class
