<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/admin/Admin.Master" CodeBehind="CouponCodes.aspx.vb" Inherits="IndiaBobbles.CouponCodes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Body" runat="server">
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:indiabobblesConnectionString %>" 
            SelectCommand="SELECT [Id], [Name], [DateCreated], [IsPercent], [Value], [Status],
	  CASE WHEN Status = 0 THEN 'Active' WHEN Status = 1 THEN 'Inactive' WHEN Status = 2 THEN 'Deleted' ELSE '' END AS [StatusText]
  FROM [dbo].[CouponCode]"
        DeleteCommand="UPDATE [dbo].[CouponCode] SET Status = 2 WHERE Id = @Id" 
            UpdateCommand="UPDATE [dbo].[CouponCode] SET [Name] = @Name, [IsPercent] = @IsPercent, [Value] = @Value, Status = @Status WHERE ID = @Id" 
            InsertCommand="INSERT INTO CategoryTag([Name], [DateCreated], [IsPercent], [Value], [Status]) 
  VALUES (@Name,GETUTCDATE(), @IsPercent, @Status, @Value)">

        <DeleteParameters>
            <asp:ControlParameter ControlID="TagGridView" Name="Id" PropertyName="SelectedValue" />
        </DeleteParameters>
        <InsertParameters>
            
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" DefaultValue="" />
            <asp:Parameter Name="IsPercent" DefaultValue="0" />
            <asp:Parameter Name="Value" DefaultValue="" />
            <asp:Parameter Name="Status" DefaultValue="0" />
            <asp:ControlParameter ControlID="TagGridView" Name="ID" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <h1>Coupon Codes</h1>
<asp:GridView ID="TagGridView" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CssClass="table" DataKeyNames="ID" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True">
    <Columns>
        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" Visible="false" ReadOnly="True" SortExpression="ID" />
        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
        <asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" />
        <asp:TemplateField HeaderText="Status" SortExpression="Status">
            <EditItemTemplate>
                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Status") %>'></asp:TextBox>
            </EditItemTemplate>
            <ItemTemplate>
                <asp:Label ID="Label1" runat="server" Text='<%# Bind("StatusText") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:BoundField DataField="Value" HeaderText="Value" SortExpression="Value" />
    </Columns>
    <PagerSettings Position="TopAndBottom" />
    <PagerStyle CssClass="paging" HorizontalAlign="Center" />
</asp:GridView>
<h2>Add Tag</h2>
<div class="row">
    <div class="col-md-6">
        <div class="p-1">
            <label for="UrlNameTextBox" class="form-label">Url Name</label>
            <asp:TextBox ID="UrlNameTextBox" ClientIDMode="Static" MaxLength="300" CssClass="form-control" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ForeColor="Red" ControlToValidate="UrlNameTextBox" Display="Dynamic" ValidationGroup="valgrp" ID="RequiredFieldValidator1" runat="server" ErrorMessage="Required"></asp:RequiredFieldValidator>
        </div>
        <div class="p-1">
            <label for="DisplayNameTextBox" class="form-label">Display Name</label>
            <asp:TextBox ID="DisplayNameTextBox" ClientIDMode="Static" MaxLength="100" CssClass="form-control" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ForeColor="Red" ControlToValidate="DisplayNameTextBox" Display="Dynamic" ValidationGroup="valgrp" ID="RequiredFieldValidator3" runat="server" ErrorMessage="Required"></asp:RequiredFieldValidator>
        </div>
        <div class="p-1">
            <label for="DescriptionTextBox" class="form-label">Description</label>
            <asp:TextBox ID="DescriptionTextBox" ClientIDMode="Static" MaxLength="2000" CssClass="form-control" runat="server"></asp:TextBox>
        </div>
        <div class="p-1">
            <label for="StatusDropdown" class="form-label">Status</label>
            <asp:DropDownList ID="StatusDropdown" CssClass="form-select" runat="server">
                <asp:ListItem Text="Active" Value="0"></asp:ListItem>
                <asp:ListItem Text="Inactive" Value="1"></asp:ListItem>
                <asp:ListItem Text="Deleted" Value="2"></asp:ListItem>
            </asp:DropDownList>
        </div>
        <div class="well p-1">
            <asp:HiddenField ID="UserIDHidden" runat="server" />
            <asp:Button ID="SaveButton" runat="server" Text="Save Tag" ValidationGroup="valgrp" CssClass="btn btn-primary" CausesValidation="true" />
        </div>
    </div>
</div>
</asp:Content>
