'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageOrder

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''NotFoundPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotFoundPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''OrderPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPanel As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ReceiptLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReceiptLink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''MessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ItemsRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemsRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''StatusDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDropDown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShippingServiceTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingServiceTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrackTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrackTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShippingNotesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingNotesTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DetailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DeleteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SlipRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlipRepeater As Global.System.Web.UI.WebControls.Repeater
End Class
