'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class ManageCoupons

    Protected WithEvents CouponDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents CouponGridView As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents CouponCodeTextBox As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents CouponCodeReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents TypeDropDown As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents ValueTextBox As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents ValueReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents ValueRegexVal As Global.System.Web.UI.WebControls.RegularExpressionValidator

    Protected WithEvents StatusDropDown As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button
End Class