<%@ Page Title="Coupon Codes" Language="vb" AutoEventWireup="false" MasterPageFile="~/admin/Admin.Master" CodeBehind="ManageCoupons.aspx.vb" Inherits="IndiaBobbles.ManageCoupons" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="Body" runat="server">
    <asp:SqlDataSource ID="CouponDataSource" runat="server"
        ConnectionString="<%$ ConnectionStrings:indiabobblesConnectionString %>"
        SelectCommand="SELECT [Id], [Name], [DateCreated], [IsPercent], [Value], [Status], CASE WHEN [Status] = 0 THEN 'Active' WHEN [Status] = 1 THEN 'Inactive' WHEN [Status] = 2 THEN 'Deleted' ELSE '' END AS [StatusText], CASE WHEN [IsPercent] = 1 THEN 'Percent' ELSE 'Flat' END AS [TypeText] FROM [CouponCode] ORDER BY [DateCreated] DESC"
        InsertCommand="INSERT INTO [CouponCode]([Name], [DateCreated], [IsPercent], [Value], [Status]) VALUES (@Name, GETUTCDATE(), @IsPercent, @Value, @Status)"
        UpdateCommand="UPDATE [CouponCode] SET [Name] = @Name, [IsPercent] = @IsPercent, [Value] = @Value, [Status] = @Status WHERE [Id] = @Id"
        DeleteCommand="UPDATE [CouponCode] SET [Status] = 2 WHERE [Id] = @Id">

        <InsertParameters>
            <asp:ControlParameter ControlID="CouponCodeTextBox" Name="Name" PropertyName="Text" />
            <asp:ControlParameter ControlID="TypeDropDown" Name="IsPercent" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="ValueTextBox" Name="Value" PropertyName="Text" />
            <asp:ControlParameter ControlID="StatusDropDown" Name="Status" PropertyName="SelectedValue" />
        </InsertParameters>

        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="IsPercent" Type="Boolean" />
            <asp:Parameter Name="Value" Type="Decimal" />
            <asp:Parameter Name="Status" Type="Byte" />
            <asp:Parameter Name="Id" Type="Int32" />
        </UpdateParameters>

        <DeleteParameters>
            <asp:ControlParameter ControlID="CouponGridView" Name="Id" PropertyName="SelectedValue" />
        </DeleteParameters>
    </asp:SqlDataSource>

    <h1>Coupon Codes</h1>

    <asp:GridView ID="CouponGridView" runat="server" CssClass="table table-striped table-bordered table-condensed"
        DataSourceID="CouponDataSource" DataKeyNames="Id" AutoGenerateColumns="False"
        AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AllowPaging="True" AllowSorting="True">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="ID" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="Name" HeaderText="Code" SortExpression="Name" />
            <asp:BoundField DataField="DateCreated" HeaderText="Date Created" SortExpression="DateCreated" DataFormatString="{0:d MMM yyyy h:mm tt}" ReadOnly="True" />
            <asp:BoundField DataField="IsPercent" HeaderText="IsPercent (0/1)" SortExpression="IsPercent" />
            <asp:TemplateField HeaderText="Type" SortExpression="TypeText">
                <ItemTemplate>
                    <%# Eval("TypeText") %>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="Value" HeaderText="Value" SortExpression="Value" DataFormatString="{0:0.##}" />
            <asp:BoundField DataField="Status" HeaderText="Status (0/1/2)" SortExpression="Status" />
            <asp:TemplateField HeaderText="Status Text" SortExpression="StatusText">
                <ItemTemplate>
                    <%# Eval("StatusText") %>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <PagerSettings Position="TopAndBottom" />
        <PagerStyle CssClass="paging" HorizontalAlign="Center" />
    </asp:GridView>

    <h2>Add Coupon</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="mb-2">
                <label for="CouponCodeTextBox" class="form-label">Coupon Code</label>
                <asp:TextBox ID="CouponCodeTextBox" runat="server" MaxLength="100" CssClass="form-control"></asp:TextBox>
                <asp:RequiredFieldValidator ID="CouponCodeReqVal" runat="server" ValidationGroup="CouponGrp" ControlToValidate="CouponCodeTextBox" CssClass="text-danger" ErrorMessage="Required" Display="Dynamic"></asp:RequiredFieldValidator>
            </div>

            <div class="mb-2">
                <label for="TypeDropDown" class="form-label">Type</label>
                <asp:DropDownList ID="TypeDropDown" runat="server" CssClass="form-select">
                    <asp:ListItem Text="Flat Amount" Value="0" />
                    <asp:ListItem Text="Percent" Value="1" />
                </asp:DropDownList>
            </div>

            <div class="mb-2">
                <label for="ValueTextBox" class="form-label">Value</label>
                <asp:TextBox ID="ValueTextBox" runat="server" MaxLength="12" CssClass="form-control"></asp:TextBox>
                <asp:RequiredFieldValidator ID="ValueReqVal" runat="server" ValidationGroup="CouponGrp" ControlToValidate="ValueTextBox" CssClass="text-danger" ErrorMessage="Required" Display="Dynamic"></asp:RequiredFieldValidator>
                <asp:RegularExpressionValidator ID="ValueRegexVal" runat="server" ValidationGroup="CouponGrp" ControlToValidate="ValueTextBox" CssClass="text-danger" ErrorMessage="Invalid value" ValidationExpression="^\d+(\.\d{1,2})?$" Display="Dynamic"></asp:RegularExpressionValidator>
            </div>

            <div class="mb-2">
                <label for="StatusDropDown" class="form-label">Status</label>
                <asp:DropDownList ID="StatusDropDown" runat="server" CssClass="form-select">
                    <asp:ListItem Text="Active" Value="0" />
                    <asp:ListItem Text="Inactive" Value="1" />
                    <asp:ListItem Text="Deleted" Value="2" />
                </asp:DropDownList>
            </div>

            <div class="mt-3">
                <asp:Button ID="SaveButton" runat="server" CssClass="btn btn-primary" Text="Save Coupon" ValidationGroup="CouponGrp" OnClick="SaveButton_Click" />
            </div>
        </div>
    </div>
</asp:Content>