'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageArticle

    '''<summary>
    '''CategorySource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategorySource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''message1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents message1 As Global.IndiaBobbles.Message

    '''<summary>
    '''HeadingLit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadingLit As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TitleTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TitleReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''MetaTitleTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MetaTitleTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''URLTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents URLTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CustomValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator1 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''TagTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TagTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TagReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TagReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SitemapCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SitemapCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''WriterTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WriterTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WriterReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WriterReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''WriterEmailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WriterEmailTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WriterEmailReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WriterEmailReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CategoryDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoryDropDown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CategoryReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoryReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''FacebookImageTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FacebookImageTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FacebookDescTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FacebookDescTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StatusDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDropDown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SlideShowCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlideShowCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''QuestionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DescTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DescReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DescReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TextTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
End Class
