'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BulkEmail

    '''<summary>
    '''StatusPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''StatusLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MemberCountLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberCountLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''OrderCountLiteral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderCountLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''RecipientsTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecipientsTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubjectTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubjectTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubjectReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubjectReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''MessageTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MessageReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EmailGroupTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailGroupTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EmailGroupReqVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailGroupReqVal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MemberRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemberRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''OrderProductFilterTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderProductFilterTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ApplyOrderFilterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ApplyOrderFilterButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ClearOrderFilterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClearOrderFilterButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OrderRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderRepeater As Global.System.Web.UI.WebControls.Repeater
End Class
