<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/admin/Admin.Master" CodeBehind="Tags.aspx.vb" Inherits="IndiaBobbles.Tags" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Body" runat="server">
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:indiabobblesConnectionString %>" SelectCommand="SELECT CT.ID, CT.UrlName, CT.Description, CASE WHEN CT.Status = 0 THEN 'Active' WHEN CT.Status = 1 THEN 'Inactive' WHEN CT.Status = 2 THEN 'Deleted' ELSE '' END AS [StatusText], CT.Status, CT.DisplayName, COUNT(PT.ID) AS ProductCount
FROM     CategoryTag AS CT LEFT OUTER JOIN
                  ProductTag AS PT ON CT.ID = PT.TagID
				  GROUP BY CT.ID, CT.UrlName, CT.Description, CT.Status, CT.DisplayName"
        DeleteCommand="UPDATE CategoryTag SET Status = 2 WHERE ID = @ID" UpdateCommand="UPDATE CategoryTag SET UrlName = @UrlName, Description = @Description, DisplayName = @DisplayName, Status = @Status WHERE ID = @ID" InsertCommand="INSERT INTO CategoryTag(UrlName, Description, ImagePath, CreateDate, CreatedBy, Status, DisplayName) VALUES (@UrlName, @Description, N'', GETDATE(), @CreatedBy, @Status, @DisplayName)">
        <DeleteParameters>
            <asp:ControlParameter ControlID="TagGridView" Name="ID" PropertyName="SelectedValue" />
        </DeleteParameters>
        <InsertParameters>
            <asp:ControlParameter ControlID="UrlNameTextBox" Name="UrlName" PropertyName="Text" />
            <asp:ControlParameter ControlID="DescriptionTextBox" Name="Description" PropertyName="Text" DefaultValue=" " />
            <asp:ControlParameter ControlID="UserIDHidden" Name="CreatedBy" PropertyName="Value" />
            <asp:ControlParameter ControlID="StatusDropdown" Name="Status" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="DisplayNameTextBox" Name="DisplayName" PropertyName="Text" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="UrlName" DefaultValue="" />
            <asp:Parameter Name="Description" DefaultValue="" />
            <asp:Parameter Name="DisplayName" DefaultValue="" />
            <asp:Parameter Name="Status" DefaultValue="0" />
            <asp:ControlParameter ControlID="TagGridView" Name="ID" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <h1>Tags</h1>
    <asp:GridView ID="TagGridView" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CssClass="table" DataKeyNames="ID" DataSourceID="SqlDataSource1" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" Visible="false" ReadOnly="True" SortExpression="ID" />
            <asp:BoundField DataField="UrlName" HeaderText="Url Name" SortExpression="UrlName" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:TemplateField HeaderText="Status" SortExpression="Status">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Status") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("StatusText") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="DisplayName" HeaderText="Display Name" SortExpression="DisplayName" />
            <asp:BoundField DataField="ProductCount" HeaderText="Product Count" ReadOnly="True" SortExpression="ProductCount" />
        </Columns>
        <PagerSettings Position="TopAndBottom" />
        <PagerStyle CssClass="paging" HorizontalAlign="Center" />
    </asp:GridView>
    <h2>Add Tag</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="p-1">
                <label for="UrlNameTextBox" class="form-label">Url Name</label>
                <asp:TextBox ID="UrlNameTextBox" ClientIDMode="Static" MaxLength="300" CssClass="form-control" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ForeColor="Red" ControlToValidate="UrlNameTextBox" Display="Dynamic" ValidationGroup="valgrp" ID="RequiredFieldValidator1" runat="server" ErrorMessage="Required"></asp:RequiredFieldValidator>
            </div>
            <div class="p-1">
                <label for="DisplayNameTextBox" class="form-label">Display Name</label>
                <asp:TextBox ID="DisplayNameTextBox" ClientIDMode="Static" MaxLength="100" CssClass="form-control" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ForeColor="Red" ControlToValidate="DisplayNameTextBox" Display="Dynamic" ValidationGroup="valgrp" ID="RequiredFieldValidator3" runat="server" ErrorMessage="Required"></asp:RequiredFieldValidator>
            </div>
            <div class="p-1">
                <label for="DescriptionTextBox" class="form-label">Description</label>
                <asp:TextBox ID="DescriptionTextBox" ClientIDMode="Static" MaxLength="2000" CssClass="form-control" runat="server"></asp:TextBox>
            </div>
            <div class="p-1">
                <label for="StatusDropdown" class="form-label">Status</label>
                <asp:DropDownList ID="StatusDropdown" CssClass="form-select" runat="server">
                    <asp:ListItem Text="Active" Value="0"></asp:ListItem>
                    <asp:ListItem Text="Inactive" Value="1"></asp:ListItem>
                    <asp:ListItem Text="Deleted" Value="2"></asp:ListItem>
                </asp:DropDownList>
            </div>
            <div class="well p-1">
                <asp:HiddenField ID="UserIDHidden" runat="server" />
                <asp:Button ID="SaveButton" runat="server" Text="Save Tag" ValidationGroup="valgrp" CssClass="btn btn-primary" CausesValidation="true" />
            </div>
        </div>
    </div>

</asp:Content>
