'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CategoryTag
    Public Property ID As Integer
    Public Property UrlName As String
    Public Property Description As String
    Public Property ImagePath As String
    Public Property CreateDate As Date
    Public Property CreatedBy As Long
    Public Property ModifiedBy As Nullable(Of Long)
    Public Property ModifyDate As Nullable(Of Date)
    Public Property Status As Byte
    Public Property DisplayName As String

    Public Overridable Property ProductTags As ICollection(Of ProductTag) = New HashSet(Of ProductTag)

End Class
