'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailMessage
    Public Property ID As System.Guid
    Public Property FromAddress As String
    Public Property ToAddress As String
    Public Property Subject As String
    Public Property Message As String
    Public Property IsRead As Boolean
    Public Property SentDate As Date
    Public Property CreateDate As Date
    Public Property IsSent As Boolean
    Public Property EmailType As Byte
    Public Property EmailGroup As String
    Public Property ReadDate As Nullable(Of Date)
    Public Property CCAdress As String
    Public Property ToName As String
    Public Property FromName As String
    Public Property LastAttempt As Date

End Class
