'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Member
    Public Property ID As Long
    Public Property Email As String
    Public Property Password As String
    Public Property Createdate As Date
    Public Property Newsletter As Boolean
    Public Property UserType As Byte
    Public Property MemberName As String
    Public Property Status As Byte
    Public Property LastLogon As Nullable(Of Date)
    Public Property DOB As Nullable(Of Date)
    Public Property Country As String
    Public Property AlternateEmail As String
    Public Property Mobile As String
    Public Property AlternateEmail2 As String
    Public Property Phone As String
    Public Property Address As String
    Public Property ModifyDate As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Long)
    Public Property LastName As String
    Public Property Gender As String
    Public Property MemberImage As String
    Public Property UserName As String

    Public Overridable Property CustomDataSources As ICollection(Of CustomDataSource) = New HashSet(Of CustomDataSource)
    Public Overridable Property CustomDataSources1 As ICollection(Of CustomDataSource) = New HashSet(Of CustomDataSource)
    Public Overridable Property CustomPages As ICollection(Of CustomPage) = New HashSet(Of CustomPage)
    Public Overridable Property CustomPages1 As ICollection(Of CustomPage) = New HashSet(Of CustomPage)
    Public Overridable Property Member1 As ICollection(Of Member) = New HashSet(Of Member)
    Public Overridable Property Member2 As Member
    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)
    Public Overridable Property PageComments As ICollection(Of PageComment) = New HashSet(Of PageComment)
    Public Overridable Property PageComments1 As ICollection(Of PageComment) = New HashSet(Of PageComment)
    Public Overridable Property Posts As ICollection(Of Post) = New HashSet(Of Post)
    Public Overridable Property Posts1 As ICollection(Of Post) = New HashSet(Of Post)
    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)
    Public Overridable Property Products1 As ICollection(Of Product) = New HashSet(Of Product)
    Public Overridable Property TopStories As ICollection(Of TopStory) = New HashSet(Of TopStory)
    Public Overridable Property UserInRoles As ICollection(Of UserInRole) = New HashSet(Of UserInRole)

End Class
