'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ID As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property MRP As Decimal
    Public Property SalePrice As Decimal
    Public Property CreatedBy As Long
    Public Property CreateDate As Date
    Public Property ModifiedBy As Nullable(Of Long)
    Public Property ModifyDate As Nullable(Of Date)
    Public Property Status As Byte
    Public Property Dimension As String
    Public Property Color As String
    Public Property Weight As String
    Public Property Material As String
    Public Property Manufacturer As String
    Public Property CareInstructions As String
    Public Property RecommendedAge As String
    Public Property CountryofOrigin As String
    Public Property Fragile As Boolean
    Public Property ShippingTime As String
    Public Property Handmade As Boolean
    Public Property ThumbPath As String
    Public Property URL As String
    Public Property ProductCode As String
    Public Property OutofStock As Boolean

    Public Overridable Property Member As Member
    Public Overridable Property Member1 As Member
    Public Overridable Property ProductPhotoes As ICollection(Of ProductPhoto) = New HashSet(Of ProductPhoto)
    Public Overridable Property ProductTags As ICollection(Of ProductTag) = New HashSet(Of ProductTag)

End Class
